/*
 * Course: CS215-00x
 * Project: Extra Task 3
 * Purpose: this program repeatedly allows the user
 *         until the user chooses to quit the program
 *         it generates the first operand: a one digit, or two digits, or three digits number
 *         it then generates a single digit integer num2 as the second operand: at the range of [1,9]
 *         to practice FOUR basic math operations: + - * and /
 *         Note there are two requirements for the questions due to the users are second graders:
 *         (1) For substraction questions, the answers cannot be negative numbers;
 *         (2) For division questions, the answers can only be whole number without reminder.
 *         it then asks the user to enter the answer to four questions:
 *         (1)num1 + num2;
 *         (2)num1 - num2;
 *         (3)num1 * num2;
 *         (4)num1 / num2;
 *         if the answer is correct, a message of congratulations should be printed;
 *         if the answer is not correct, a message should be printed showing the correct answer.
 *Author: (your name)
 */

#include <iostream>
#include <cstdlib>
#include <ctime>
#include <algorithm>   // for the transform() function
#include <string>
#include "MathOperations.h"

using namespace std;

// declare global variable (constant only, avoid using global variable!)
const int LEN = 2;  // represents the length of a array: to store one character and one terminator

string toUpper(const string& original);
void collectAnswer(const MathOperations& question);

int main()
{
    // define constants for the ranges of two operands
    const int ANSWERMIN = 1;    // Minimum value of the possible answer
    const int ANSWERMAX = 100;  // Maximum value of the possible answer
    const int OP2MIN = 1;       // Minimum value of the second operand
    const int OP2MAX = 9;       // Maximum value of the second operand

    int num1;          // The first operand for the operations
    int num2;          // The second operand for the operations
    string choice;     // The user's choice: either answer the question or quit

    // Seed the random number generator.
    srand(time(nullptr));

    cout << "Do you want to practice four basic math operations?" << endl;
    cout << "Press Enter to continue or press  N(o) to quit...";
    getline(cin, choice);
    // convert the string stored in choice into all uppercase
    // by calling toUpper() function 
    choice = toUpper(choice);

    while (choice != "N" && choice != "NO")
    {
        MathOperations question;

        // while generating the questions to solve, it needs to satisfy two requirements:
        // (1) For subtraction questions, the answer cannot be negative number;
        // (2) For division questions, the answer can only be whole number
        // In order to satisfy the above two requirement, num1 is generated by num2 * PA (PA is in the range of [1, 100])
        // Generate a number at the range of [1,100]
        int PA = ANSWERMIN + rand() % (ANSWERMAX - ANSWERMIN + 1);
        // Generate a single digit number at the range of [1,9] as the second operand
        num2 = OP2MIN + rand() % (OP2MAX - OP2MIN + 1);
        // Generate first operand either a sigle digit or two digits number
        num1 = PA * num2;

        // With the same operands: num1 and num2
        // (1)Produce an addition question; print the question;  then call collectAnswer function
        // (2)Produce a substraction question; print the question;  then call collectAnswer function
        // (3)Produce a multiplication question; print the question;  then call collectAnswer function
        // (4)Produce a division question; print the question;  then call collectAnswer function
        // your code starts here...











        cout << "Do you want to practice three basic math operations?" << endl;
        cout << "Press Enter to continue or press  N(o) to quit...";
        getline(cin, choice);
        // convert the string stored in choice into all uppercase
        choice = toUpper(choice);
    }

    cout << "Thank you for practicing Basic Math Operations." << endl;
    return 0;
}


/*
 * Returns the string which transforms each character of the parameter into upper case
 * @param original: the original string
 *  const call by reference (no copy is made for efficiency, safe to the argument)
 * @return a new string which transforms each character of the parameter into upper case
 *  (algorithm header file is needed for the definition of transform function)
 */
string toUpper(const string& original)
{
    string result = original;
    transform(original.begin(), original.end(), result.begin(), ::toupper);
    return result;
}


/* pass an object using const call by reference
 * (no copy is made for efficiency and no side-effect, safe to the argument)
 */
void collectAnswer(const MathOperations& question)
{
    int studentAnswer; // The student's answer
    cout << "Please type your answer: " << endl;
    cin >> studentAnswer;
    cin.ignore(256, '\n');

    // if user-input is not a valid integer, allow the user to try again and again...
    while (cin.fail())
    {
        cin.clear();
        cin.ignore(256, '\n');
        cout << "Invalid input! Please try again..." << endl;
        cout << "Please type your answer: " << endl;
        cin >> studentAnswer;
        cin.ignore(256, '\n');
    }

    // get the valid integer input, then check if it is correct
    question.checkAnswer(studentAnswer);
    if (question.checkAnswer(studentAnswer))
        cout << "Congratulations! " << studentAnswer << " is the right answer." << endl;
    else
        cout << "Sorry, the correct answer is " << question.getAnswer() << "." << endl;
}
